/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Datos.InscripcionData;
<<<<<<< HEAD
import Entidades.Inscripcion;
=======
import Datos.MateriaData;
import Entidades.Alumno;
import Entidades.Inscripcion;
import Entidades.Materia;
import java.util.ArrayList;
import java.util.List;
>>>>>>> ff0d7cf7d5aefd4c48f95d9a86b2dbb6cd6f9797
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nacho
 */
public class Inscripciones extends javax.swing.JInternalFrame {
<<<<<<< HEAD
    private DefaultTableModel modelo = new DefaultTableModel();
=======
    private DefaultTableModel modelo;
    private List<Materia> listaM;
    private List<Alumno> listaA;
>>>>>>> ff0d7cf7d5aefd4c48f95d9a86b2dbb6cd6f9797
    
    
    public Inscripciones() {
        initComponents();
        armarCabesera();
    }
<<<<<<< HEAD
    
    
=======
  private void cargarAlumnos(){
      for(Alumno item : listaA){
          jcbAlumno.addItem(item);
      }
  }  
  private void armarCabeceraTabla(){
      ArrayList<Object> filaCabecera = new ArrayList<>();
      filaCabecera.add("ID");
      filaCabecera.add("Nombre");
      filaCabecera.add("Año");
      for(Object it:filaCabecera){
          modelo.addColumn(it);
      }
      jTable.setModel(modelo);
  }
public void FormularioInscripcion(){
    initComponents();
    aData = new AlumnoData();
    listaA = aData.listarAlumnos();
    modelo = new DefaultTableModel();
    mData= new MateriaData();
    cargarAlumnos();
    armarCabeceraTabla();
    
    insData = new InscripcionData();

}
private void borrarFilaTabla(){
    int indice = modelo.getRowCount()-1;
    
    for(int i = indice; i >= 0; i--){
        modelo.removeRow(i);
    }
}
private void cargarDatosNoInscriptas(){
    borrarFilaTabla();
    Alumno selec= (Alumno)jcbAlumno.getSelectedItem();
    listaM =  (ArrayList<Materia>) insData.obtenerMateriasNoCursadas(selec.getIdAlumno());
    for(Materia m: listaM){
        modelo.addRow(new Object[] {m.getIdMateria(),m.getNombre(),m.getAnioMateria()});
    }
}
private void cargarDatosInscriptas(){
    borrarFilaTabla();
    Alumno selec= (Alumno)jcbAlumno.getSelectedItem();
    List<Materia> lista  = insData.obtenerMateriasCursadas(selec.getIdAlumno());
    for(Materia m: lista){
        modelo.addRow(new Object[] {m.getIdMateria(),m.getNombre(),m.getAnioMateria()});
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
>>>>>>> ff0d7cf7d5aefd4c48f95d9a86b2dbb6cd6f9797
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTMaterias = new javax.swing.JTable();
        jBGuardar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setTitle("                                  Formulario de Inscripcion");
        setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Formulario de inscripcion");

        jLabel3.setText("Seleccione un Alumno:");

        jcbAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAlumnoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Listado de Materias:");

<<<<<<< HEAD
        jRadioButton1.setText("Materias Inscriptas");
=======
        MateriasInscriptasNoInscriptas.add(jrbMateriasInscriptas);
        jrbMateriasInscriptas.setText("Materias Inscriptas");
        jrbMateriasInscriptas.setFocusCycleRoot(true);
        jrbMateriasInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMateriasInscriptasActionPerformed(evt);
            }
        });
>>>>>>> ff0d7cf7d5aefd4c48f95d9a86b2dbb6cd6f9797

        jRadioButton2.setText("Materias no Inscriptas");

        jTMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTMaterias);

<<<<<<< HEAD
        jBGuardar.setText("Inscribir");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
=======
        jbInscribir.setText("Inscribir");
        jbInscribir.setEnabled(false);
        jbInscribir.addActionListener(new java.awt.event.ActionListener() {
>>>>>>> ff0d7cf7d5aefd4c48f95d9a86b2dbb6cd6f9797
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

<<<<<<< HEAD
        jButton2.setText("Anular inscripsion");
=======
        jbAnularInscripcion.setText("Anular inscripsion");
        jbAnularInscripcion.setEnabled(false);
        jbAnularInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnularInscripcionActionPerformed(evt);
            }
        });
>>>>>>> ff0d7cf7d5aefd4c48f95d9a86b2dbb6cd6f9797

        jButton3.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(40, 40, 40)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(70, 70, 70)
                        .addComponent(jRadioButton2)
                        .addGap(71, 71, 71))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jBGuardar)
                .addGap(52, 52, 52)
                .addComponent(jButton2)
                .addGap(51, 51, 51)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGuardar)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

<<<<<<< HEAD
    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        InscripcionData id = new InscripcionData();
        Inscripcion inscripcion = null;
        id.guardarInscripcion(inscripcion);
    }//GEN-LAST:event_jBGuardarActionPerformed
=======
    private void jbInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInscribirActionPerformed
        int filaSeleccionada= jTable.getSelectedRow();
        if(filaSeleccionada !=-1){
            
        Alumno a = (Alumno) jcbAlumno.getSelectedItem();
        
        int idMateria = (Integer) modelo.getValueAt(filaSeleccionada, 0);
        String nombreMateria = (String)modelo.getValueAt(filaSeleccionada, 1);
        int anio = (Integer)modelo.getValueAt(filaSeleccionada, 2);
        Materia m = new Materia(idMateria,nombreMateria,anio,true);
        
        Inscripcion i = new Inscripcion(a,m,0);
        insData.guardarInscripcion(i);
    }
    }//GEN-LAST:event_jbInscribirActionPerformed

    private void jbAnularInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnularInscripcionActionPerformed
                int filaSeleccionada= jTable.getSelectedRow();
        if(filaSeleccionada !=-1){
             Alumno a = (Alumno) jcbAlumno.getSelectedItem();
             int idMateria=(Integer)modelo.getValueAt(filaSeleccionada, 0);
             
             insData.borrarInscripcionMateriaAlumno(a.getIdAlumno(), idMateria);
        } 
    }//GEN-LAST:event_jbAnularInscripcionActionPerformed

    private void jrbMateriasNoInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMateriasNoInscriptasActionPerformed
      borrarFilaTabla();
        jrbMateriasInscriptas.setSelected(false);
         cargarDatosNoInscriptas();
         jbAnularInscripcion.setEnabled(false);
         jbInscribir.setEnabled(true);
   
    }//GEN-LAST:event_jrbMateriasNoInscriptasActionPerformed

    private void jrbMateriasInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMateriasInscriptasActionPerformed
        borrarFilaTabla();
         jrbMateriasNoInscriptas.setSelected(false);
         cargarDatosInscriptas();
         jbAnularInscripcion.setEnabled(true);
         jbInscribir.setEnabled(false);
       
    }//GEN-LAST:event_jrbMateriasInscriptasActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed
>>>>>>> ff0d7cf7d5aefd4c48f95d9a86b2dbb6cd6f9797

    private void jcbAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbAlumnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTMaterias;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

private void armarCabesera(){
    modelo.addColumn("ID");
    modelo.addColumn("Nombre");
    modelo.addColumn("Año");
    jTMaterias.setModel(modelo);
}


}
